#!/usr/bin/env bash
# Story of passwd
while IFS=: read -r u p uid gid info home shell; do
echo "The user $u is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $p, more info about the user here: $info"
done < /etc/passwd
