#!/usr/bin/env bash
# Manages PID file and handles signals
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM
while true; do echo "To infinity and beyond"; sleep 2; done
